name: Aufgaben CI-CD Workflows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
       - name: Repository holen
         uses: actions/checkout@v4

       - name: Aktuelles Verzeichnis anzeigen
         run: pwd

       - name: kernel-/Systeminfo 
         run: uname -a

       - name: aktuelles Datum anzeigen
         run: date

       - name: Verzeichnisinhalt auflisten
         run: ls -la

       - name: Textdatei
         run: |
            mkdir -p reports
            echo "System Report" > reports/system-report.txt
            echo "Date: $(date)" >> reports/system-report.txt
            echo "Runner: ${{RUNNER_NAME}}" >> reports/system-report.txt
            echo "Directory: $(pwd)" >> reports/system-report.txt
            echo "Contents:" >> reports/system-report.txt
            ls -la >> reports/system-report.txt

       - name: Show report file
          run: cat reports/system-report.txt
