name: Environment Config Demo

on:
  push:
  workflow_dispatch:

jobs:
  config-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decide environment
        id: env
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "ENV=prod" >> $GITHUB_OUTPUT
          else
            echo "ENV=dev" >> $GITHUB_OUTPUT
          fi

      - name: Load config file
        id: config
        run: |
          ENV=${{ steps.env.outputs.ENV }}

          if [ "$ENV" = "prod" ]; then
            FILE="config/prod.env"
          else
            FILE="config/dev.env"
          fi

          echo "FILE=$FILE" >> $GITHUB_OUTPUT

          echo "=== Selected Config File ==="
          echo "$FILE"

      - name: Read config values
        run: |
          FILE=${{ steps.config.outputs.FILE }}

          echo "=== Environment Info ==="
          echo "Environment: ${{ steps.env.outputs.ENV }}"
          echo "Config file: $FILE"

          echo "=== Loaded Values ==="
          while IFS='=' read -r key value
          do
            echo "$key = $value"
          done < "$FILE"